name: study_connect
description: StudyConnect - A collaborative learning platform for students
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Navigation
  go_router: ^12.1.3

  # Database
  sqflite: ^2.3.0
  path: ^1.8.3

  # UI & Fonts
  google_fonts: ^6.1.0

  # Utilities
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  image_picker: ^1.0.4


  file_picker: ^6.1.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    -