# StudyConnect Phase 2 - Complete pubspec.yaml

name: study_connect
description: StudyConnect Phase 2 - A collaborative study platform for college students
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Phase 1 - Core Dependencies
  sqflite: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  crypto: ^3.0.3

  # Phase 1 - UI & Fonts
  google_fonts: ^6.1.0
  animations: ^2.0.8

  # Phase 2 - Social Media Features
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  permission_handler: ^11.1.0

  # Phase 2 - Real-time Features
  flutter_local_notifications: ^16.3.0
  workmanager: ^0.5.1

  # Phase 2 - UI Enhancements
  cached_network_image: ^3.3.0
  flutter_staggered_grid_view: ^0.7.0
  photo_view: ^0.14.0

  # Phase 2 - Utilities
  intl: ^0.19.0
  uuid: ^4.2.1
  mime: ^1.0.4
  url_launcher: ^6.2.2

  # Phase 2 - Performance
  visibility_detector: ^0.4.0
  flutter_cache_manager: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  # Phase 1 & 2 Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/

  # Phase 2 Fonts (Google Fonts handles this automatically)
  # Custom fonts can be added here if needed

# Phase 2 Configuration
flutter_native_splash:
  color: "#2196F3"
  image: assets/images/app_logo.png
  android_12:
    icon_background_color: "#2196F3"
    image: assets/images/app_logo.png

# Phase 2 Android Configuration
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#2196F3"
  adaptive_icon_foreground: "assets/images/app_logo.png"