name: study_connect
description: StudyConnect Phase 1 - SQLite authentication and splash screen
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Database
  sqflite: ^2.3.0
  path: ^1.8.3

  # State Management
  provider: ^6.1.1

  # UI & Fonts
  google_fonts: ^6.1.0

  # Storage
  shared_preferences: ^2.2.2

  # Crypto for password hashing
  crypto: ^3.0.3

  # Form validation
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Add assets folder (create this later)
  # assets:
  #   - assets/images/
  #   - assets/icons/