name: study_connect
description: StudyConnect - Phase 2 Social Learning Platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Firebase (KEPT)
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6

  # Database (KEPT)
  sqflite: ^2.3.0
  path: ^1.8.3

  # State Management (KEPT)
  provider: ^6.1.1

  # Navigation (KEPT)
  go_router: ^12.1.3

  # UI & Design (KEPT)
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0

  # Animations (KEPT)
  lottie: ^2.7.0
  animations: ^2.0.8

  # Utilities (KEPT)
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  permission_handler: ^11.1.0

  # Phase 2 Social Features (NEW - MOBILE ONLY)
  image_picker: ^1.0.4
  flutter_local_notifications: ^16.1.0
  intl: ^0.19.0
  uuid: ^4.1.0
  url_launcher: ^6.2.1
  photo_view: ^0.14.0
  flutter_staggered_grid_view: ^0.7.0
  visibility_detector: ^0.4.0
  flutter_cache_manager: ^3.3.1
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
